sudo: false
language: node_js
node_js:
  - "8.3"
  - "lts/*"
  - "node"
before_install:
  - npm install -g greenkeeper-lockfile
install:
  - npm install
  - cd dashboard && npm install
before_script: 
  - greenkeeper-lockfile-update
  - npm run build
  - cd dashboard && ./node_modukes/.bin/tsc -p tsconfig.json
after_script: greenkeeper-lockfile-upload
notifications:
  disabled: true
cache:
  directories:
    - "node_modules"
    - "dashboard/node_modules"
